const cfg=window.SUNRISE_CONFIG, client=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
async function boot(){const {data:{session}}=await client.auth.getSession(); if(session)showDash();else $("loginBox").hidden=false}
async function showDash(){$("loginBox").hidden=true;$("dashboard").hidden=false;await loadTemplates();await loadOrders()}
$("loginForm").onsubmit=async e=>{e.preventDefault();const {error}=await client.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});$("loginMsg").textContent=error?error.message:"";if(!error)showDash()};
$("logout").onclick=async()=>{await client.auth.signOut();location.reload()};
async function loadTemplates(){const {data,error}=await client.from("templates").select("*").order("created_at",{ascending:false});if(error){$("templatesAdmin").textContent=error.message;return}$("templatesAdmin").innerHTML=(data||[]).map(t=>`<div class="admin-row"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.category)} • 📸 ${t.required_photos} • 🎬 ${t.required_videos} • ${t.is_active?"Active":"Hidden"}</div></div><div class="row-actions"><button onclick="editTemplate('${t.id}')">Edit</button><button onclick="toggleTemplate('${t.id}',${!t.is_active})">${t.is_active?"Hide":"Show"}</button><button onclick="deleteTemplate('${t.id}')">Delete</button></div></div>`).join("")||"<p>No templates.</p>";window._templates=data||[]}
window.editTemplate=id=>{const t=window._templates.find(x=>x.id===id);if(!t)return;$("tmId").value=t.id;$("tmHeading").textContent="Edit Template";$("tmTitle").value=t.title;$("tmCategory").value=t.category;$("tmDescription").value=t.description||"";$("tmType").value=t.preview_type;$("tmPreview").value=t.preview_url||"";$("tmPhotos").value=t.required_photos;$("tmVideos").value=t.required_videos;$("tmSong").checked=t.song_required;$("tmPrice").value=t.price??"";$("tmPremiumPrice").value=t.premium_price??"";$("tmRevisions").value=t.premium_revisions??2;$("tmDuration").value=t.premium_duration_seconds??60;$("tmActive").checked=t.is_active;$("templateModal").hidden=false}
window.toggleTemplate=async(id,active)=>{await client.from("templates").update({is_active:active}).eq("id",id);loadTemplates()}
window.deleteTemplate=async id=>{if(confirm("Delete this template?")){await client.from("templates").delete().eq("id",id);loadTemplates()}}
$("newTemplate").onclick=()=>{$("templateForm").reset();$("tmId").value="";$("tmHeading").textContent="Add Template";$("tmActive").checked=true;$("templateModal").hidden=false};
$("tmClose").onclick=()=>$("templateModal").hidden=true;
$("templateModal").onclick=e=>{if(e.target===$("templateModal"))$("templateModal").hidden=true};
$("templateForm").onsubmit=async e=>{e.preventDefault();const obj={title:$("tmTitle").value.trim(),category:$("tmCategory").value,description:$("tmDescription").value.trim(),preview_type:$("tmType").value,preview_url:$("tmPreview").value.trim(),required_photos:+$("tmPhotos").value,required_videos:+$("tmVideos").value,song_required:$("tmSong").checked,price:$("tmPrice").value?+$("tmPrice").value:null,premium_price:$("tmPremiumPrice").value?+$("tmPremiumPrice").value:null,premium_revisions:+$("tmRevisions").value,premium_duration_seconds:+$("tmDuration").value,is_active:$("tmActive").checked};const id=$("tmId").value;const res=id?await client.from("templates").update(obj).eq("id",id):await client.from("templates").insert(obj);$("tmMsg").textContent=res.error?res.error.message:"Saved!";if(!res.error){setTimeout(()=>{$("templateModal").hidden=true;loadTemplates()},500)}};
async function loadOrders(){const {data,error}=await client.from("orders").select("*, templates(title), order_files(*)").order("created_at",{ascending:false});if(error){$("ordersAdmin").textContent=error.message;return}$("ordersAdmin").innerHTML=(data||[]).map(o=>`<div class="order-row"><div><b>${esc(o.order_code)} — ${esc(o.templates?.title||"Deleted template")}</b><div>${esc(o.name)} • ${esc(o.mobile)} • ${esc(o.email)} • ${esc(o.instagram_username)}<br><b>${o.plan==="premium"?"💎 Premium":"🆓 Free Collab"}</b> • Payment: ${esc(o.payment_status)} • Watermark: ${o.watermark?"Yes":"No"} • Revisions: ${o.revision_limit}</div><div class="muted">${new Date(o.created_at).toLocaleString()} • ${o.order_files?.length||0} files</div></div><div class="row-actions"><select onchange="setStatus('${o.id}',this.value)"><option ${o.status==="New"?"selected":""}>New</option><option ${o.status==="Processing"?"selected":""}>Processing</option><option ${o.status==="Completed"?"selected":""}>Completed</option><option ${o.status==="Cancelled"?"selected":""}>Cancelled</option></select>${(o.order_files||[]).map(f=>`<button onclick="downloadFile('${esc(f.file_path)}')">Download ${esc(f.file_name)}</button>`).join("")}</div></div>`).join("")||"<p>No orders yet.</p>"}
window.setStatus=async(id,status)=>{await client.from("orders").update({status}).eq("id",id);loadOrders()};
window.downloadFile=async path=>{const {data,error}=await client.storage.from("customer-orders").createSignedUrl(path,300);if(error)alert(error.message);else window.open(data.signedUrl,"_blank")};
boot();
